name: Build liblcf for armel

on:
  push:
  pull_request:

jobs:
  build-armel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone liblcf source
        run: |
          git clone --depth=1 https://github.com/EasyRPG/liblcf.git

      - name: Set up dockcross script (armv5 / soft-float)
        run: |
          docker run --rm ghcr.io/dockcross/linux-armv5 > ./dockcross-armel
          chmod +x ./dockcross-armel

      - name: Build liblcf with dockcross
        run: |
          ./dockcross-armel bash -c "
            apt-get update && apt-get install -y cmake pkg-config
            cd liblcf
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j$(nproc)
          "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liblcf-armel-build
          path: liblcf/build/
