name: Build liblcf for armel with xcross

on:
  push:
  pull_request:

jobs:
  build-armel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone liblcf source
        run: git clone --depth=1 https://github.com/EasyRPG/liblcf.git

      - name: Build liblcf with xcross (armel)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace xcross/armel \
          /bin/bash -c "
            apt-get update && apt-get install -y cmake pkg-config build-essential
            cd /workspace/liblcf
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j$(nproc)
          "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liblcf-armel-build
          path: liblcf/build/

