name: Build liblcf for armel

on:
  push:
  pull_request:

jobs:
  build-armel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and compile liblcf for armel
        run: |
          docker buildx build --platform linux/arm/v5 --load -t liblcf-armel-build . --progress=plain

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liblcf-armel-build
          path: build/
